version: "3.9" # optional since v1.27.0
services:
  <%= apiname %>_db_dev:
    image: mariadb:10.3.38
    container_name: <%= apiname %>
    environment:
      - MARIADB_USER=root
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    ports:
      - <%= dev_port %>:3306
    volumes:
      - <%= apiname %>:/var/lib/mysql

volumes:
  <%= apiname %>:
    driver: local
